accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import signup

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

projects/urls.py
from django.urls import path

from projects.views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
)

urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
]

tasks/urls.py
from django.urls import path

from tasks.views import (
    TaskCreateView,
    TaskListView,
    TaskUpdateView,
    TaskFieldsUpdateView,
    TaskDetailView,
)

urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
    path("<int:pk>/taskupdate/", TaskFieldsUpdateView.as_view(), name="update_task"),
    path("<int:pk>/tasknotes/", TaskDetailView.as_view(), name="show_notes"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.urls import reverse_lazy

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    project_image = models.ImageField(
        null=True, blank=True, upload_to="images/"
    )
    members = models.ManyToManyField(
        USER_MODEL,
        related_name="projects",
    )

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models
from django.conf import settings


USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    notes = models.TextField(blank=True)

    project = models.ForeignKey(
        "projects.Project",
        related_name="tasks",
        on_delete=models.CASCADE,
    )
    assignee = models.ForeignKey(
        USER_MODEL,
        null=True,
        related_name="tasks",
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# Create your views here.


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

projects/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from projects.models import Project


# Create your views here.


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/detail.html"


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/create.html"
    fields = ["name", "description", "project_image", "members"]
    success_url = reverse_lazy("show_project")

    def form_valid(self, form):
        item = form.save(commit=False)
        item.assignee = self.request.user
        item.save()
        form.save_m2m()
        return redirect("show_project", pk=item.id)

tasks/views.py
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.detail import DetailView
from tasks.models import Task

# Create your views here.


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/create.html"
    fields = ["name", "start_date", "due_date", "project", "assignee", "notes"]
    # redirect to detail page of task's project after successful form submit

    def get_success_url(self):
        return reverse_lazy("show_project", args=[self.object.project.id])


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/list.html"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ["is_completed"]

    def get_success_url(self):
        return reverse_lazy("show_my_tasks")

class TaskFieldsUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ["name", "start_date", "due_date", "is_completed", "notes"]
    template_name = "tasks/update.html"

    def get_success_url(self):
        return reverse_lazy("show_project", args=[self.object.project.id])


class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task
    template_name = "tasks/detail.html"

accounts/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'css/app.css' %}">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
        <title>Tracker</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'show_my_tasks' %}">My tasks<span class="material-icons md-18">list</span></a>
                        </li>
                        <li>
                            <a href="{% url 'list_projects' %}">My projects<span class="material-icons md-18" id="build">build</span></a>
                        </li>
                        <li>
                            <a href="{% url 'logout' %}">Logout<span class="material-icons md-18">logout</span></a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'login' %}">Login<span class="material-icons md-18">login</span></a>
                        </li>
                        <li>
                            <a href="{% url 'signup' %}">Signup<span class="material-icons md-18">touch_app</span></a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            {% block content %}
            {% endblock content %}
        </main>
    </body>
</html>

projects/templates/projects/create.html
{% extends 'base.html' %}

{% block content %}
    <div class="project-form">
        <h1>Add a new project</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
{% endblock content %}

projects/templates/projects/detail.html
{% extends 'base.html' %}
{% load markdownify %}

{% block content %}
    <div class="project-detail">
        <h1>{{ project.name }}</h1>
        {{ project.description|markdownify }}
        <br>
        {% if project.project_image %}
        <img src="{{project.project_image.url}}">
        {% endif %}
        <h2>Tasks</h2>
        <p><a href="{% url 'create_task' %}"><span class="material-icons md-18">
            add_circle
            </span>Add task</a></p>

        {% if project.tasks.all %}
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Assignee</th>
                        <th>Start date</th>
                        <th>Due date</th>
                        <th>Is completed</th>
                        <th>Notes</th>
                        <th>Update</th>
                    </tr>
                </thead>
                <tbody>
                    {% for task_info in project.tasks.all %}
                        <tr>
                            <td>{{ task_info.name }}</td>
                            <td>{{ task_info.assignee }}</td>
                            <td>{{ task_info.start_date|date:"D d M Y"}}</td>
                            <td>{{ task_info.due_date|date:"D d M Y"}}</td>
                            {% if task_info.is_completed == False %}
                                <td><span class="material-icons">close</span></td>
                            {% else %}
                                <td><span class="material-icons">done</span></td>
                            {% endif %}

                            {% if task_info.notes|length >= 1 %}
                            <td><a href="{% url 'show_notes' task_info.id%}">View Notes</a></td>
                            {% else %}
                            <td><span class="material-icons">
                                horizontal_rule
                                </span></td>
                            {% endif %}
                            
                            <td><a href="{% url 'update_task' task_info.id%}">
                                <span class="material-icons">
                                    update
                                    </span></a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
        <p>This project has no tasks<p>
        {% endif %}
    </div>
{% endblock content %}

projects/templates/projects/list.html
{% extends 'base.html' %}

{% block content %}
<div class="project-list">
    <h1>My Projects</h1>
    <p><a href="{% url 'create_project' %}"><span class="material-icons md-18">
        add_circle
        </span>Add project</a></p>
    {% if project_list %}
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number of tasks</th>
                </tr>
            </thead>
            <tbody>
                {% for project_info in project_list %}
                    <tr>
                        <td>
                            <a href="{% url 'show_project' project_info.id %}">
                                {{ project_info.name }}</a>
                        </td>
                        <td>{{ project_info.tasks.all|length }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>You are not assigned to any projects</p>
    {% endif %}
</div>
{% endblock content %}

tasks/templates/tasks/create.html
{% extends 'base.html' %}

{% block content %}
    <div class="task-form">
        <h1>Create a new task</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
{% endblock content %}

tasks/templates/tasks/detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="task-detail">
        <h1>{{task.name}}</h1>
            <h2>Notes</h2>
                <p>{{task.notes}}</p>

                <a href="{% url 'show_project' task.project.id %}">
                    <span class="material-icons md-18">arrow_back</span>
                </a>
    </div>
{% endblock content %}

tasks/templates/tasks/list.html
{% extends 'base.html' %}

{% block content %}
    <div class="my-tasks-list">
        <h1>My Tasks</h1>
        {% if task_list %}
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Start date</th>
                        <th>End date</th>
                        <th>Is completed</th>
                    </tr>
                    <thead>
                        <tbody>
                            {% for task_info in task_list %}
                                <tr>
                                    <td><a href="{% url 'show_project' task_info.project.id%}">{{task_info.name}}</a></td>
                                    <td>{{task_info.start_date|date:'D d M Y'}}</td>
                                    <td>{{task_info.due_date|date:'D d M Y'}}</td>

                                    {% if task_info.is_completed == False %}
                                        <td>
                                            <form method="post" action="{% url 'complete_task' task_info.id %}">
                                                {% csrf_token %}
                                                <input type="hidden" name="is_completed" value="True">
                                                <button id="complete_button">Complete</button>
                                            </form>
                                        </td>
                                    {% else %}
                                        <!--<td>{{task_info.is_completed|yesno:'Done, '}}</td>-->
                                        <td><span class="material-icons">
                                            done
                                            </span></td>
                                    {% endif %}

                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
        {% else %}
            <p>You have no tasks</p>
        {% endif %}
    </div>
{% endblock content %}

tasks/templates/tasks/update.html
{% extends 'base.html' %}

{% block content %}
<div class="task-update-form">
    <h1>Update Task</h1>
        <form method = "post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="button">Update</button>
        </form>
        <br>
        <a href="{% url 'show_project' task.project.id %}">
            <span class="material-icons md-18">arrow_back</span>
        </a>
</div>
{% endblock content %}